name: Test & Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Use PostgresSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: "nc_games_test"
          postgresql user: "user"
          postgresql password: "password"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: PGDATABASE=nc_games_test PGUSER=user PGPASSWORD=password npm t
